<form method="get" action="" >
<label for="locale">Choose a language:</label>

<select name="locale" id="locale" onchange="submit()">
  <option value="none">None</option>
  <option value="nl_NL">Dutch</option>
  <option value="en">English</option>
  <option value="en_US">Us</option>
</select>
<input type="hidden" name="bearer" value=<?php echo $_GET['bearer']; ?>>
</form>

<h2><?php echo $this->locale->_('Sign up') ?> </h2>
<div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
    <?php echo isset($message)?$message:''; ?>
</div>


<?php echo $this->tag->form("signup/signup"); ?>
<p>
    <label for="name"><?php echo $this->locale->_('Name'); ?></label>
    
    <?php echo $this->tag->textField("name"); ?>
</p>
<p>
    <label for="email"><?php echo $this->locale->_('email'); ?></label>
    
    <?php echo $this->tag->textField("email"); ?>
</p>
<p>
    <label for="password"><?php echo $this->locale->_('password'); ?></label>
    
    <?php echo $this->tag->textField("password"); ?>
</p>
<p>
    <div for="drop-down">
        <label for="name"><?php echo $this->locale->_('Choose a role'); ?></label>
        
        <select for="role" name="role">
            <?php echo $options; ?>
        </select>
    </div>
    
</p>
<?php echo $this->tag->submitButton("Submit"); ?>
</form>
